services:
  php:
    container_name: php-server
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      PHP_IDE_CONFIG: "serverName=ace3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5173:5173
    volumes:
      - ./mtg-grimorio-site:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - container-network

  nginx:
    container_name: nginx-server
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '8080:80'
      - '443:443'
    volumes:
      - ./mtg-grimorio-site:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - container-network

  mysql:
    container_name: mysql-server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - container-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - container-network
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: mtg_data
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd

  phpmyadmin:
    container_name: phpmyadmin-server
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - container-network
    environment:
      PMA_HOST: mysql-server
    depends_on:
      - mysql

networks:
  container-network:
    driver: bridge


volumes:
  container-data:
    driver: local